### ISSUE TITLE
Validates inputs for various introduction questions

### ISSUE THREAD

**Issue by devender-yadav** [saumye1/nitkkr-alumni-telegram-group-bot#6]
Tasks:

- [x] Validate batch year, email address and branch
- [x]  Store location and other strings as lowercase strings, so that there is no error while fetching
- [x] Unit test cases

**Comment by saumye1** [comment]
- [ ] store location and other strings as lowercase strings, so that there is no error while fetching

**Comment by devender-yadav** [comment]
@saumye1  added in the description itself so that we can see it as a task.

**Comment by saumye1** [comment]
I unit tested every function manually and on another test bot, as the function are implemented under bot.on('text') event.
